-----------------------------------------
-- Slacker's Addon Depot: Database.lua --
-----------------------------------------

local appName, app = ...

-- Strings
app.Name = "Slacker's Addon Depot"
app.NameLong = app:Colour(app.Name)
app.NameShort = app:Colour("SAD")
app.NamePrefix = "SlackAddonDepot"
_G["BINDING_NAME_SLACKERSADDONDEPOT"] = app.Name
_G["BINDING_NAME_SLACKWARE"] = "Slackware"

-- Textures
app.Icon = "Interface\\Icons\\inv_tinkermodule_blue"
app.IconReady = CreateSimpleTextureMarkup("Interface\\RaidFrame\\ReadyCheck-Ready")
app.IconNotReady = CreateSimpleTextureMarkup("Interface\\RaidFrame\\ReadyCheck-NotReady")
app.IconLMB = CreateAtlasMarkup("housing-hotkey-icon-leftclick")
app.IconRMB = CreateAtlasMarkup("housing-hotkey-icon-rightclick")
app.IconNew = CreateAtlasMarkup("UI-Journeys-GreatVault-Tag-new")
app.IconNone = "Interface\\Icons\\inv_misc_questionmark"

app.Professions = {
	{ tradeSkillLineID = 171, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_alchemy") },
	{ tradeSkillLineID = 164, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_blacksmithing") },
	{ tradeSkillLineID = 333, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_enchanting") },
	{ tradeSkillLineID = 202, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_engineering") },
	{ tradeSkillLineID = 773, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_inscription") },
	{ tradeSkillLineID = 755, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_jewelcrafting") },
	{ tradeSkillLineID = 165, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_leatherworking") },
	{ tradeSkillLineID = 197, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_tailoring") },
	{ tradeSkillLineID = 182, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_herbalism") },
	{ tradeSkillLineID = 186, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_mining") },
	{ tradeSkillLineID = 393, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_skinning") },
	{ tradeSkillLineID = 185, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_cooking") },
	{ tradeSkillLineID = 356, icon = CreateSimpleTextureMarkup("Interface\\Icons\\ui_profession_fishing") },
	{ tradeSkillLineID = 794, icon = CreateSimpleTextureMarkup("Interface\\Icons\\trade_archaeology") },
}

app.Enum = {
	Condition = {
		Character = 1,
		Name = 2,
		Level = 3,
		Realm = 4,
		Profession = 5,
		Class = 6,
	},
	ConditionState = {
		Any = 1,
		All = 2,
		IsLessThan = 3,
		Is = 4,
		IsAnyOf = 5,
		IsGreaterThan = 6,
		IsNot = 7,
		IsNotAnyOf = 8,
		StartsWith = 9,
		EndsWith = 10,
		Contains = 11,
		DoesNotContain = 12,
	},
}
app.ValidStates = {
	[app.Enum.Condition.Character] = {
		[app.Enum.ConditionState.IsAnyOf] = true,
		[app.Enum.ConditionState.IsNotAnyOf] = true,
	},
	[app.Enum.Condition.Name] = {
		[app.Enum.ConditionState.Is] = true,
		[app.Enum.ConditionState.IsNot] = true,
		[app.Enum.ConditionState.StartsWith] = true,
		[app.Enum.ConditionState.EndsWith] = true,
		[app.Enum.ConditionState.Contains] = true,
		[app.Enum.ConditionState.DoesNotContain] = true,
	},
	[app.Enum.Condition.Level] = {
		[app.Enum.ConditionState.IsLessThan] = true,
		[app.Enum.ConditionState.Is] = true,
		[app.Enum.ConditionState.IsGreaterThan] = true,
	},
	[app.Enum.Condition.Realm] = {
		[app.Enum.ConditionState.Is] = true,
		[app.Enum.ConditionState.IsNot] = true,
		[app.Enum.ConditionState.StartsWith] = true,
		[app.Enum.ConditionState.EndsWith] = true,
		[app.Enum.ConditionState.Contains] = true,
		[app.Enum.ConditionState.DoesNotContain] = true,
	},
	[app.Enum.Condition.Profession] = {
		[app.Enum.ConditionState.IsAnyOf] = true,
		[app.Enum.ConditionState.IsNotAnyOf] = true,
	},
	[app.Enum.Condition.Class] = {
		[app.Enum.ConditionState.IsAnyOf] = true,
		[app.Enum.ConditionState.IsNotAnyOf] = true,
	},
}

app.WikiCategories = {
	["enUS"] = {
		["Action Bars"] = true,
		["Auctions"] = true,
		["Buffs & Debuffs"] = true,
		["Chat"] = true,
		["Collections"] = true,
		["Combat"] = true,
		["Data Broker"] = true,
		["Development Tools"] = true,
		["Dungeons & Raids"] = true,
		["Equipment"] = true,
		["Expansion Features"] = true,
		["Housing"] = true,
		["Inventory"] = true,
		["Libraries"] = true,
		["Loot"] = true,
		["Map"] = true,
		["Media"] = true,
		["Minigames"] = true,
		["Other"] = true,
		["Pet Battles"] = true,
		["Professions"] = true,
		["PvP"] = true,
		["Quests"] = true,
		["Roleplay"] = true,
		["UI Overhaul"] = true,
		["Unit Frames"] = true,
		["User Interface"] = true,
	},

	["deDE"] = {
		["Aktionsleisten"] = true,
		["Auktionen"] = true,
		["Buffs & Debuffs"] = true,
		["Chat"] = true,
		["Kriegsmeutesammlungen"] = true,
		["Kampf"] = true,
		["Datenbroker"] = true,
		["Entwicklungstools"] = true,
		["Dungeons & Schlachtzüge"] = true,
		["Ausrüstung"] = true,
		["Erweiterungsfeatures"] = true,
		["Behausung"] = true,
		["Inventar"] = true,
		["Bibliotheken"] = true,
		["Beute"] = true,
		["Karte"] = true,
		["Medien"] = true,
		["Minispiele"] = true,
		["Anderes"] = true,
		["Haustierkämpfe"] = true,
		["Berufe"] = true,
		["PvP"] = true,
		["Quests"] = true,
		["Rollenspiel"] = true,
		["UI-Überholung"] = true,
		["Einheitenfenster"] = true,
		["Benutzerinterface"] = true,
	},

	["esES"] = {
		["Barras de acción"] = true,
		["Subastas"] = true,
		["Beneficios y Perjuicios"] = true,
		["Chat"] = true,
		["Colecciones de banda guerrera"] = true,
		["Combate"] = true,
		["Intermediario de Datos"] = true,
		["Herramientas de Desarrollo"] = true,
		["Mazmorras y bandas"] = true,
		["Equipo"] = true,
		["Características"] = true,
		["Hogares"] = true,
		["Inventario"] = true,
		["Bibliotecas"] = true,
		["Botín"] = true,
		["Mapa"] = true,
		["Medios"] = true,
		["Minijuegos"] = true,
		["Otros"] = true,
		["Duelos de mascotas"] = true,
		["Profesiones"] = true,
		["JcJ"] = true,
		["Misiones"] = true,
		["Juego de rol"] = true,
		["Renovación de la Interfaz de Usuario"] = true,
		["Marcos de unidades"] = true,
		["Interfaz de usuario"] = true,
	},

	["esMX"] = {
		["Barras de acción"] = true,
		["Subastas"] = true,
		["Beneficios y Perjuicios"] = true,
		["Chat"] = true,
		["Colecciones de tropa"] = true,
		["Combate"] = true,
		["Intermediario de Datos"] = true,
		["Herramientas de Desarrollo"] = true,
		["Calabozos y bandas"] = true,
		["Equipo"] = true,
		["Características de expansiones"] = true,
		["Viviendas"] = true,
		["Inventario"] = true,
		["Bibliotecas"] = true,
		["Botín"] = true,
		["Mapa"] = true,
		["Medios"] = true,
		["Minijuegos"] = true,
		["Otros"] = true,
		["Duelos de mascotas"] = true,
		["Profesiones"] = true,
		["JcJ"] = true,
		["Misiones"] = true,
		["Juego de rol"] = true,
		["Renovación de la Interfaz de Usuario"] = true,
		["Marcos de unidades"] = true,
		["Interfaz de usuario"] = true,
	},

	["frFR"] = {
		["Barres d’action"] = true,
		["Ventes"] = true,
		["Améliorations et Affaiblissements"] = true,
		["Discussion"] = true,
		["Collections du bataillon"] = true,
		["Combat"] = true,
		["Courtier de Données"] = true,
		["Outils de Développement"] = true,
		["Donjons et raids"] = true,
		["Équipement"] = true,
		["Contenu d’extension"] = true,
		["Logis"] = true,
		["Inventaire"] = true,
		["Bibliothèques"] = true,
		["Butin"] = true,
		["Carte"] = true,
		["Médias"] = true,
		["Mini-jeux"] = true,
		["Autre"] = true,
		["Combats de mascottes"] = true,
		["Métiers"] = true,
		["JcJ"] = true,
		["Quêtes"] = true,
		["Jeu de rôle"] = true,
		["Révision de l'Interface Utilisateur"] = true,
		["Portraits d'unités"] = true,
		["Interface utilisateur"] = true,
	},

	["itIT"] = {
		["Barre delle azioni"] = true,
		["Aste"] = true,
		["Benefici e penalità"] = true,
		["Chat"] = true,
		["Collezioni della Brigata"] = true,
		["Combattimento"] = true,
		["Data Broker"] = true,
		["Strumenti di sviluppo"] = true,
		["Spedizioni e incursioni"] = true,
		["Equipaggiamento"] = true,
		["Contenuti specifici per espansioni"] = true,
		["Alloggi"] = true,
		["Inventario"] = true,
		["Librerie"] = true,
		["Bottino"] = true,
		["Mappa"] = true,
		["Media"] = true,
		["Minigiochi"] = true,
		["Altro"] = true,
		["Battaglie fra pet"] = true,
		["Professioni"] = true,
		["PvP"] = true,
		["Missioni"] = true,
		["Gioco di Ruolo"] = true,
		["Revisione dell'interfaccia utente"] = true,
		["Riquadri delle unità"] = true,
		["Interfaccia utente"] = true,
	},

	["koKR"] = {
		["액션 바"] = true,
		["경매"] = true,
		["버프 및 디버프"] = true,
		["대화"] = true,
		["수집"] = true,
		["전투"] = true,
		["데이터 브로커"] = true,
		["개발 도구"] = true,
		["던전 및 공격대"] = true,
		["장비"] = true,
		["확장팩 특징"] = true,
		["하우징"] = true,
		["소지품"] = true,
		["라이브러리"] = true,
		["전리품"] = true,
		["지도"] = true,
		["미디어"] = true,
		["미니게임"] = true,
		["기타"] = true,
		["애완동물 대전"] = true,
		["전문 기술"] = true,
		["PvP"] = true,
		["퀘스트"] = true,
		["역할 수행"] = true,
		["UI 개조"] = true,
		["유닛프레임"] = true,
		["사용자 인터페이스"] = true,
	},

	["ptBR"] = {
		["Barras de ação"] = true,
		["Leilões"] = true,
		["Bônus e Penalidades"] = true,
		["Bate-papo"] = true,
		["Coleções do Bando de Guerra"] = true,
		["Combate"] = true,
		["Corretor de Dados"] = true,
		["Ferramentas de Desenvolvimento"] = true,
		["Masmorras e Raides"] = true,
		["Equipamento"] = true,
		["Características da Expansão"] = true,
		["Moradia"] = true,
		["Inventário"] = true,
		["Bibliotecas"] = true,
		["Saque"] = true,
		["Mapa"] = true,
		["Mídia"] = true,
		["Minijogos"] = true,
		["Outro"] = true,
		["Batalhas de mascotes"] = true,
		["Profissões"] = true,
		["JxJ"] = true,
		["Missões"] = true,
		["Interpretação de Papel"] = true,
		["Reformulação da Interface do Usuário"] = true,
		["Quadros de unidade"] = true,
		["Interface do usuário"] = true,
	},

	["ruRU"] = {
		["Панели команд"] = true,
		["Аукционы"] = true,
		["Баффы и дебаффы"] = true,
		["Чат"] = true,
		["Коллекции отряда"] = true,
		["Бой"] = true,
		["Посредник данных"] = true,
		["Инструменты разработки"] = true,
		["Подземелья и рейды"] = true,
		["Экипировка"] = true,
		["Особый контент"] = true,
		["Жилье"] = true,
		["Инвентарь"] = true,
		["Библиотеки"] = true,
		["Добыча"] = true,
		["Карта"] = true,
		["Медиа"] = true,
		["Мини-игры"] = true,
		["Другое"] = true,
		["Битвы питомцев"] = true,
		["Профессии"] = true,
		["PvP"] = true,
		["Задания"] = true,
		["Ролевая игра"] = true,
		["Переработка интерфейса"] = true,
		["Рамки юнитов"] = true,
		["Интерфейс пользователя"] = true,
	},

	["zhCN"] = {
		["动作条"] = true,
		["拍卖"] = true,
		["增益和减益"] = true,
		["聊天"] = true,
		["战团藏品"] = true,
		["战斗"] = true,
		["数据管理"] = true,
		["开发工具"] = true,
		["地下城和团队副本"] = true,
		["装备"] = true,
		["特色更新"] = true,
		["住宅"] = true,
		["物品栏"] = true,
		["函数库"] = true,
		["战利品"] = true,
		["地图"] = true,
		["材质"] = true,
		["迷你游戏"] = true,
		["其它"] = true,
		["宠物对战"] = true,
		["专业"] = true,
		["PvP"] = true,
		["任务"] = true,
		["角色扮演"] = true,
		["UI重构"] = true,
		["单位框架"] = true,
		["用户界面"] = true,
	},

	["zhTW"] = {
		["快捷列"] = true,
		["拍賣"] = true,
		["增益與減益"] = true,
		["對話"] = true,
		["戰隊收藏"] = true,
		["戰鬥"] = true,
		["資料管理"] = true,
		["開發工具"] = true,
		["地城與團隊"] = true,
		["裝備"] = true,
		["資料片特色"] = true,
		["房屋"] = true,
		["物品欄"] = true,
		["函式庫"] = true,
		["戰利品"] = true,
		["地圖"] = true,
		["材質"] = true,
		["迷你遊戲"] = true,
		["其他"] = true,
		["寵物對戰"] = true,
		["專業技能"] = true,
		["PvP"] = true,
		["任務"] = true,
		["角色扮演"] = true,
		["UI重構"] = true,
		["單位框架"] = true,
		["使用者介面"] = true,
	},
}
